### ISSUE TITLE
commit hook and deleting file

### ISSUE THREAD

**Issue by benneti** [nrdxp/nixflk#110]
**Describe the bug**
I tried to delete a file but then git commit failed.
As I do not now the reason exactly I simply moved .git/hooks temporarily to another place, then I was able to add the commit message.

**To Reproduce**
1. Delete a file
2. commit
3. try to "git commit -m asdf"

**Expected behavior**
Git commit hook should not interfere with usual git actions.

**Comment by nrdxp** [comment]
This should have been fixed a few days ago with e7d9abfdcdc49ef6f9f28443ec48bce307fdb0a2

Have you updated since then?

**Comment by benneti** [comment]
ah sorry indeed, did the merge with master after i realized this.
Thanks for the heads up
