### ISSUE TITLE
devshell changes

### ISSUE THREAD

**Issue by benneti** [nrdxp/nixflk#124]
This is more of a question:
Due to devshell changing a lot at the moment it is quite inconvenient to `nix flake update` often because then the direnv could break (happens a lot for me). 
The current relevant change is moving the git settings: https://github.com/numtide/devshell/commit/8fdf9b74bc4901151117f347b1bf87c6353c5073 , I think it is necessary to import git as an extra module now but they only document this approach for a TOML configuration.

On a broader scope do you think there is a viable approach for devshell (i.e. I do not think there is a simple way to exclude one repo from the flake update when recreating the whole lock file)?

**Comment by nrdxp** [comment]
you can update whatever inputs you want like so `nix flake update --update-input devshell`, will only update devshell leaving all other inputs the same.

**Comment by benneti** [comment]
Yes I know, but I would need the inverse of this to update everything but devshell, but maybe it would be simplest to write a small update script that updates all Inuits like you describe and not devshell.

**Comment by nrdxp** [comment]
That's not a bad idea. I'm also about to push some changes to update everything to the newest devshell, and moving a lot of the shell to a devshell.toml to simplify things a bit.

**Comment by benneti** [comment]
Thanks that solves it; now the documentation of devshell can be applied simpler!
