### ISSUE TITLE
Multiarch support?

### ISSUE THREAD

**Issue by tgunnoe** [nrdxp/nixflk#17]
**Is your feature request related to a problem? Please describe.**
Not necessarily, although i don't think this will work with arm builds. With the growing rise of arm as a desktop/laptop replacement, it's important to have templates like these adaptable to those needs.

**Describe the solution you'd like**
I don't have any solution to provide, but I do see that there are some x86-64 assumptions in `flake.nix` and probably other places.  Ideally down to generating an image for an arm system would work. For example, have `hosts/niximg-x86-64.nix` and `hosts/niximg-aarch64.nix`

**Additional context**
I have been monitoring and studying this repository for a few weeks now and am definitely interested and like how things are shaping up.  I've been leaning towards using it in place of what ive already started, but I have several arm-based machines that I want to work well with my configuration.

**Comment by nrdxp** [comment]
This is definitely something I want to work towards. Just hasn't been urgent for me as I don't have any arm machines I'm using right now. Once I'm finished with some of my current experiements in templating, I can probably tackle this fairly easily with the help of [flake-utils](https://github.com/numtide/flake-utils). I'm always open to a PR as well, if you have the time.

**Comment by nrdxp** [comment]
I went ahead and opened #18 which should close this issue. Please have a look. More work is needed within nixpkgs itself to support some arm platforms, but this is a good first start.
