### ISSUE TITLE
Unable to use custom pkgs in home.packages

### ISSUE THREAD

**Issue by JamieMagee** [nrdxp/nixflk#21]
I have created a custom package for my VPN setup that I want to add to `home.packages`, but I get the error `undefined variable 'myvpn'` when trying to build. It works correctly when adding to `environment.SystemPackages`.

I've created `pkgs/networking/myvpn/default.nix` and added it to `pkgs/default.nix`. Is there something I'm missing?

**Comment by nrdxp** [comment]
the full qualified path should be `home-manager.users.<username>.home.packages` as in the following:
https://github.com/nrdxp/nixflk/blob/67801f4345a8955c1f0938fe2519a875671af895/users/nrd/default.nix#L23-L27

Just to make sure, is this how you are declaring your packages? I haven't actually used the home-manager package feature as you can see I am forcing an empty list for that option so I'm not sure if they work or not, however it could be that you're simply declaring the wrong option name. Lemme know if that helps.

**Comment by JamieMagee** [comment]
@nrdxp Okay, let me give a more concrete example. I've pushed a [branch to my repo called `vscode`](https://github.com/JamieMagee/nixos-config/commit/1562a7b375447b6785ea30bdb1383b807c081341). It contains a package called `my-extensions` which builds my vscode extensions.

I can successfully import this via `home.packages = [ pkgs.my-extensions.csharp ];`, however attempting to import via `programs.vscode.extensions = [ pkgs.my-extensions.csharp ];` I get the error `attribute 'my-extensions' missing`.

Any suggestions?

**Comment by nrdxp** [comment]
Sorry for long delay. It's obvious that the package is out of scope for the `programs` attribute.

Are you building your package from the [pkgs](../tree/template/pkgs) directory by properly adding its definition and calling it via the [default.nix](../tree/template/pkgs/default.nix)? If so, I can't imagine why this wouldn't work. Building packages any other way isn't supported.

Let me know if this is still an issue. Thanks
