### ISSUE TITLE
New generation on rebuild?

### ISSUE THREAD

**Issue by cyrinux** [nrdxp/nixflk#27]
**Describe the bug**
I need to run `nixos-rebuild switch --flake '/etc/nixos#myvm' ` to get a new boot loader generation at boot.

**To Reproduce**
1. nix-shell
2. rebuild vm switch
3. here constat at boot there is no new generation (EFI boot loader != grub)

**Expected behavior**
I'm new to nixos, i try to understand all the mecanic. Using some simple receipe, give me a new generation at boot on each `switch` but with nixflk i feel i need to `rebuild myvm switch` and `nixos-rebuild switch --flake '/etc/nixos#myvm'.

**Additional context**
Is-it normal? Maybe i missunderstood something?

Thanks for this project 👍🏻

**Comment by nrdxp** [comment]
I haven't had this issue. What boot loader are you using?

**Comment by cyrinux** [comment]
Hi, I'm using bootctl, while, i find some others dotfiles using Nixflk where guys do the same, first use the 'rebuild host switch', then 'nixos-rebuild switch'. 
Any idea ? 
Thanks

**Comment by nrdxp** [comment]
The problem is the `-E` flag being passed to sudo in the shell.nix. I'm opening a pr to remove it and it should fix the issue.

**Comment by cyrinux** [comment]
Thanks you I will retry.
