### ISSUE TITLE
Adding the overlay of a nix flake

### ISSUE THREAD

**Issue by jokogr** [nrdxp/nixflk#28]
:wave: This template gave me the right boost to start porting my client machine configuration to flakes, many thanks!

I would like to add the overlay that another nix flake provides, e.g., [nixpkgs-wayland](https://github.com/colemickens/nixpkgs-wayland).

What would be the most optimal way to do so? Since I am talking about packages that both system and user (via home-manager configuration) might use, I am particularly interested in a solution which addresses both cases.

**Comment by nrdxp** [comment]
The semantics for pulling overlays from other flakes should be improved, but for now anything added to nixflk's overlays output attribute is automatically added to the NixOS system overlays. 

So simply wire the overlays from the two you mention into said overlays attribute and they'll be available for you.

**Comment by jokogr** [comment]
> So simply wire the overlays from the repo you mentioned into said overlays attribute and they'll be available for you.

Sorry for my late comment to this, but it is still not totally clear to me how to do so. I saw the example of a custom overlay at https://github.com/nrdxp/nixflk/blob/993a79e61edeb811537927cbb504769013eaf37d/profiles/laptop/default.nix#L48-L61, but:

1. AFAIK the flake as an attribute is not accessible to profiles, i.e., one has to use it at `hosts/default.nix`.
2. Should the `nixpkgs-overlays` path in NIX_PATH defined [there](https://github.com/nrdxp/nixflk/blob/993a79e61edeb811537927cbb504769013eaf37d/hosts/default.nix#L33) be updated somehow?

In the end I've added the overlay in the overrides section [there](https://github.com/nrdxp/nixflk/blob/993a79e61edeb811537927cbb504769013eaf37d/hosts/default.nix#L50), but I would like to hear other people's opinion on that.

**Comment by nrdxp** [comment]
Right [here](https://github.com/nrdxp/nixflk/blob/template/flake.nix#L25). Something like:
```
overlays = (attrValues self.overlays) ++ [ 
  otherFlake.overlays.yourOverlay
];

I'm thinking about adding an internal "extras" flake that is not exposed to the outside world but is wired into the default config so adding things from other flakes can be less painful. Until then, this should do.

**Comment by nrdxp** [comment]
I'm reopening to close with a PR I am about to submit. Essentially, I have added an `externOverlays` in `flake.nix` to which you can easily add your external overlays and they will be available for your NixOS configurations.
