### ISSUE TITLE
Permission denied

### ISSUE THREAD

**Issue by bbigras** [nrdxp/nixflk#4]
**Describe the bug**

**To Reproduce**
1. git clone https://github.com/nrdxp/nixflk.git
2. cd nixflk/
3. nix-shell
4. git checkout -b moi template
5. nixos-generate-config --show-hardware-config > ./hosts/new_host.nix
6. sudo ln -s $PWD /etc/nixos
7. git add hosts/new_host.nix
8. rebuild new_host switch

I get:
```
[...]
building '/nix/store/yk0507743hp82yldxmbkvsxdzfwzv1jw-nixos-system-new_host-20.03.20191229.1e23245.drv'...
[207 built, 376 copied (992.9 MiB), 238.2 MiB DL]
updating GRUB 2 menu...
mkdir /boot/grub: Permission denied at /nix/store/hdana4ajhbdz24pl1f20jfbq8izm2kcn-install-grub.pl line 81.
````

and if I use sudo I get:
```
[nix-shell:~/nixflk]$ sudo rebuild new_host switch
[sudo] password for bbigras:
error: experimental Nix feature 'nix-command' is disabled
```

I wonder if it's caused by sudo stripping some env vars.

**Expected behavior**

**Additional context**
 - system: `"x86_64-linux"`
 - host os: `Linux 4.19.92, NixOS, 19.09.1776.b926503738c (Loris)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.4pre20191022_9cac895`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by nrdxp** [comment]
yeah it is. I am setting NIX_CONF_DIR to set some experimental nix features. Try putting sudo -E in from of rebuild to preserve it. I'll submit a patch to do this by default.

**Comment by bbigras** [comment]
> Try putting sudo -E in from of rebuild to preserve it.

That did the trick. Thanks.
