### ISSUE TITLE
specialisations break the `system` argument

### ISSUE THREAD

**Issue by lourkeur** [nrdxp/nixflk#46]
**Describe the bug**
When the NixOS specialisations feature is used and any NixOS module evaluates the system attribute in its arguments, an EvalError occurs when instantating.

Introduced by 684804eb

[relevant nixpkgs snippet](https://github.com/NixOS/nixpkgs/blob/9e6737710c4fb2613850e699178b23d54f1a3261/nixos/modules/system/activation/top-level.nix#L1)

**To Reproduce**
1. Check [Minimal Working Example](https://github.com/lourkeur/nixflk/tree/issue46)

**Expected behavior**
The configuration should build cleanly.

**Additional context**

**Comment by nrdxp** [comment]
I'm unable to reproduce this after checking out your mentioned branch and running `nix flake check`. Also tried `rebuild iso`. What exactly is the error your getting, or what command are you running to produce the error on this branch?

**Comment by nrdxp** [comment]
I can't remember what my initial impetus was for adding this to `extraArgs`. I am assuming it was to access system, which should also be available via `nixpkgs.system`, which apparently, I did't know at the time. This, it seems that the best solution is simply to remove the `extraArgs` attribute all together and if you need to reference your current system in your config do something like so:
```nix
{ config, ... }:
{
    lib.whatIsMySystem = config.nixpkgs.system; 
}
```

**Comment by lourkeur** [comment]
I would say `pkgs.system` is slightly more future-proof since it comes somewhat directly from flake.nix rather than through some NixOS snippets that set the default value that we don't control. otherwise. It's also shorter.

**Comment by nrdxp** [comment]
good point I'll rebase the pr
