### ISSUE TITLE
add zoxide

### ISSUE THREAD

**Issue by blaggacao** [nrdxp/nixflk#53]
[zoxide](https://github.com/cole-h/nixos-config/search?q=zoxide) on [github](https://github.com/ajeetdsouza/zoxide)

**Comment by nrdxp** [comment]
I have no experience with zoxide, as I've created a custom skim [alt-c command](https://github.com/nrdxp/nixflk/blob/template/profiles/develop/zsh/default.nix#L17) to quickly change directories based on zsh's cdr command.

That's the beauty of profiles though. Feel free to add it to core, or to your own own developer profile.

**Comment by berbiche** [comment]
Some things that might be of interest to you @blaggacao : 
- fzf provides an `alt-c` keybinding to fuzzy find a folder and `cd` to it
- [broot](https://github.com/Canop/broot) is a more interactive and feature-full fzf to navigate directories (and more)

**Comment by blaggacao** [comment]
I think this can be closed for the time being, thank you for the tips!
