### ISSUE TITLE
bad idea to have make-linux-fast-again by default?

### ISSUE THREAD

**Issue by bbigras** [nrdxp/nixflk#6]
I don't know if it's possible to import `imports = [ ../profiles ]` directly but someone importing `../profiles/misc` might not realize that it will disable the meltdown/spectre mitigations.

Maybe it should only be importable directly with the path containing something like:
`DISABLE_SECURITY_I_KNOW_THE_RISK`.

**Comment by nrdxp** [comment]
Yeah, your probably right. I was thinking as much. Perhaps removing it from misc and renaming it to something like `disable_mitigations.nix` would be enough. If you really think it is necessary, we could define a custom option like `mitigations.acceptRisk` and use an assertion in the profile which fails if this is not true with a message like:
```
You must accept explicitly accept the risk of running without mitigations by setting mitigations.acceptRisk = true;
```

**Comment by bbigras** [comment]
Thanks :+1:
