### ISSUE TITLE
Build installer iso from unstable nixpkgs.

### ISSUE THREAD

**Issue by Maj-majormajormajor** [nrdxp/nixflk#63]
**Is your feature request related to a problem? Please describe.**
To run `nixos-install --flake` directly from an installer iso, the `--impure` argument is required. The unstable version of "${modulesPath}/installer/cd-dvd/installation-cd-minimal.nix" provides this argument, it isn't in nixos. I want to build an installer iso that has the unstable version of nixos-install.

**Describe the solution you'd like**
I don't know how to do this within the design of this template. I'm pretty new to nix, so my limited understanding of this template may very well be wrong.

AFAIKT, the only mechanism to use packages from unstable is via the overlays mechanism. I don't know how that relates to directly importing the `installer-cd-minimal.nix`. I tried to find what package provides `nixos-install`, but didn't get very far in the nix source code.

I managed to work around this in a very hacky way. I replaced all references to nixos with master.

Maybe a module can be added that provides an installer.enable option along with an installer.fromUnstable option.

**Comment by nrdxp** [comment]
I've been meaning to add a simple mechanism for module override from master, similar to packages; it's almost done. Should have a PR soon.

**Comment by blaggacao** [comment]
For what it's worth, doing the same for `sdImage` requires to emulate renaming of [util linux](https://github.com/NixOS/nixpkgs/commit/bc49a0815ae860010b4d593b02f00ab6f07d50ea) see specifically [this change](https://github.com/NixOS/nixpkgs/commit/bc49a0815ae860010b4d593b02f00ab6f07d50ea#diff-8003c2260c96c7783ef908628a113f692cc8fd94e54cce78c915131db6a008ac).

This change might also affect other installers.

**Comment by blaggacao** [comment]
Unfortunately an overlay of the form:
```nix
final: prev: {
  util-linux = prev.utillinux;
}
```

doesn't do the trick since this overlay is incompatible with master (since overlays are applied on both, `nixos` & `master`), see:

```console
[flk]$ flk sd
error: --- EvalError ---------------------------------------------------------------------------------------------- nix
at: (657:15) in file: /nix/store/6l6hv9pyfmznqmxkk77bbig0a9wsqslp-source/pkgs/top-level/aliases.nix

   656|   usbguard-nox = usbguard; # added 2019-09-04
   657|   utillinux = util-linux; # added 2020-11-24
      |               ^
   658|   uzbl = throw "uzbl has been removed from nixpkgs, as it's unmaintained and uses insecure libraries";

infinite recursion encountered
```

**Comment by blaggacao** [comment]
for general's public information, I'm drawing a [very distinct line on avoiding mismatches on my attempt to extract the implicit abstract interfaces hidden in this repo out into flake-utils](https://github.com/numtide/flake-utils/pull/18/files#diff-79c5531512c8fa0e4522e5d82d96fc2d93b75040e0a197cb0a94c7cb0b2c19b3R79-R83).
