### ISSUE TITLE
Can't add custom pkgs to systemPackages.

### ISSUE THREAD

**Issue by Maj-majormajormajor** [nrdxp/nixflk#65]
**Describe the bug**
Importing packages from the pkgs directory results in an error.

> error: --- EvalError --- nix
> at: (13:34) in file: /nix/store/d6dwnk6fnml3l19ch409w8nmvq3hkkrv-source/hosts/niximg.nix
> 
>     12|   networking.networkmanager.enable = true;
>     13|   environment.systemPackages = [ pkgs.libinih ];
>       |                                  ^
>     14| }
> 
> attribute 'libinih' missing

**To Reproduce**
1. Checkout repo
2. Modify niximg.nix to include the line `environment.systemPackages = [ pkgs.libinih ];` and `{ modulesPath, pkgs, ... }: {` at the top.
3. Run `flk img` in the nix-shell (after fixing the bug https://github.com/nrdxp/nixflk/pull/64)

**Expected behavior**
I expected the image to build.
According to DOC.md:

> All expressions in both modules/list.nix and pkgs/default.nix are available globally, anywhere else in the repo. They are additionally included in the nixosModules and overlay flake outputs, respectively. Packages are automatically included in the packages output as well.

**Additional context**
I pulled directly from this repo, latest commit (09f0bbd). Reverting to the commit before seems to work (9f561b8cead52cd7840ca0bcf75def8f9eb9d207).

**Comment by nrdxp** [comment]
Fixed by 00b35136c341606eb2428f898b4c8832f331f70d.
