### ISSUE TITLE
host specific externModules

### ISSUE THREAD

**Issue by benneti** [nrdxp/nixflk#70]
**Is your feature request related to a problem? Please describe.**
As briefly described in https://github.com/nrdxp/nixflk/issues/44#issuecomment-756378163 there is a problem with externModules if they are supposed to be host specific (like for nixos-hardware).

**Describe the solution you'd like**
A similarly simple solution to the externModules but host specific would be great.

**Additional context**
I created this issue because https://github.com/nrdxp/nixflk/issues/44#issuecomment-756378163 is closed but the problem is not fully solved yet.

**Comment by nrdxp** [comment]
Perhaps we could treat nixos-hardware as a special case and wire up a path via [specialArgs](https://github.com/nrdxp/nixflk/blob/7ec9a15be3e9d6ea8a294e713ecf33cecd29f555/hosts/default.nix#L23-L26).

**Comment by benneti** [comment]
indeed this seems to work, do you want a PR to add nixos-hardware to the template?
If so I would be happy to create one!

**Comment by nrdxp** [comment]
That would be great

**Comment by benneti** [comment]
I'll close this as nixos-hardware is now supported and users have a documentation for similar flakes, see https://github.com/nrdxp/nixflk/pull/95.
