### ISSUE TITLE
ovoverlay import mechanics don't seem to allow file name attribute discrepancy and also do not distinguish between nixos and master

### ISSUE THREAD

**Issue by blaggacao** [nrdxp/nixflk#76]
Because of
https://github.com/nrdxp/nixflk/blob/d0fe508da20695bd72c1a5eebd3cb113778366ac/flake.nix#L51

in conjunction with

https://github.com/nrdxp/nixflk/blob/d0fe508da20695bd72c1a5eebd3cb113778366ac/lib/utils.nix#L89-L92

https://github.com/nrdxp/nixflk/blob/d0fe508da20695bd72c1a5eebd3cb113778366ac/overlays/kakoune.nix#L13

would not be made available in `pkgs`.

In general, I'm not sure if "too much magic" here is really a win or if overlays could be managed in a more transparent manner.

I really like the way how flake-utils's simpleFlake commands name spacing (see #60).
That approach doesn't limit overlaying "stock" packages, though, through a little extra helper that would read overlays from a non  name spaced portion of the overlay file:

```nix
final: prev: {
   nixflk = {}; # name spaced overlays -- sharing friendly as `self.overlay` (namespaced, too!)
   utillinux = prev.util-linux; # non name spaced overlays -- ought not to be  exported as `self.overlay` (sic!) but available under `self.overlays.utillinux`
}
```

---

On the other hand it seems that we need a way to target an overlay either at `master` or at `nixos`, since on the contrary we expose the users to [nasty and unexpected side effects](https://github.com/nrdxp/nixflk/issues/63#issuecomment-757566201) of the implementation detail that `genPackages` targets both branches.

**Comment by blaggacao** [comment]
As for overlays on master: Couldn't we just drop overlays application on `master`? It seems there is no good UX that doesn't cause loads of troubles down the road.

**Comment by nrdxp** [comment]
We definitely need to simplify the semantics here. Originally, the name discrepency was on purpose to allow for "utility" overlays, such as `kakoune-config` that are available inside the NixOS config, but not as an export.

In general though, I want a simpler and more robust overlay interface.

**Comment by blaggacao** [comment]
Indeed it is: :wink:

```
at: (72:22) in file: /nix/store/x1jl3zbjvds5x8yvf0vanpxs3p5zfpgx-source/hosts/default.nix

    71|                 overlay = pkg: final: prev: {
    72|                   "${pkg.pname}" = pkg;
      |                      ^
    73|                 };

attribute 'pname' missing
(use '--show-trace' to show detailed location information)
```
