### ISSUE TITLE
implement apps as fallback or not at all

### ISSUE THREAD

**Issue by blaggacao** [nrdxp/nixflk#79]
https://github.com/nrdxp/nixflk/blob/d0fe508da20695bd72c1a5eebd3cb113778366ac/flake.nix#L88-L104

[`nix run` falls back to inspecting the `self.packages` attribute set](https://github.com/NixOS/nix/blob/master/src/nix/run.md#flake-output-attributes).

app declarations are only needed when in `packages.<system>.<pname>` and `/bin/<name>` <pname> and <name> are not euqal, for example:

`packages.<system>.coreutils`
but:
`/bin/cat`

It appears to me for the sake of simplicity, the app generation could be dropped. Those naming conflicts are extremely rare and the user could probably declare apps manually in such cases.

**Comment by blaggacao** [comment]
I think I'll avoid implementing apps in https://github.com/numtide/flake-utils/pull/18 for the time beeing.

**Comment by nrdxp** [comment]
Since the filtering of apps requires building the package to test for `bin` dir, your probably right.
