### ISSUE TITLE
Home manager on Non-nixos systems

### ISSUE THREAD

**Issue by Pacman99** [nrdxp/nixflk#83]
**Is your feature request related to a problem? Please describe.**
I believe that at the moment any home manager configuration you describe in nixflk cannot be used on a non-nixos system, even though this is a known use case of home manager.

**Describe the solution you'd like**
An easy way to apply home manager configurations on non-nixos systems with the existing solution.

 This could maybe be some command that takes in a user and applies the home-manager.users.<input user> to the current home directory.

 Or perhaps each user in home-manager.users could get an export in the flake.nix so they can be applied with nixos-rebuild(I think this is possible). I'm still learning flakes, so I'm not sure about implementation details. 

I think home manager configurations can be exported as packages with the activationPackage attribute, so maybe a package for each user.

**Describe alternatives you've considered**
I think you could make a home.nix that takes in the relevant config and pass that to hm switch.
Also there might already be a way to do this with nixflk and I just don't know.

**Additional context**
This was discussed on the home-manager repo: https://github.com/nix-community/home-manager/issues/1510. It looks like the configuration input for home-manager is a file, so I'm not sure how that would work with the way nixflk is formatted, since the users files include other things for the nixos configuration.

**Comment by nrdxp** [comment]
I've been thinking about this for a while now, but since I don't have any experience using home-manager outside of NixOS, I haven't had the proper impetus to implement it.

I think the easiest way to fix it would be to include the nixos dependant user declarations in it's own file under `users/<username>`, and ensuring all the home-manager stuff is imported from this file.

**Comment by Pacman99** [comment]
I was hoping to try and find a solution that doesn't require changing the nixflk format or add extra requirements to the format. 

I just saw this: https://discourse.nixos.org/t/example-use-nix-flakes-with-home-manager-on-non-nixos-systems/10185/9
It looks like the configuration attribute can also be a config function. I bet a function could be written that just pulls the appropriate home-managers.users set for the user. And homeDirectory and pulled from users.users.<username>

I think maybe the flake.nix can output homeConfigurations with a configuration for each user in home-manager.users. And then the process would be to build that configuration's activationPackage and run the activate script. That could be automated in the flk script. 

Does that seem like a possible method? I'll see if I can implement it later.

**Comment by nrdxp** [comment]
That sounds perfectly feasible. Like I said though, I've never used home-manager outside of NixOS, so I'm not sure if there's anything obvious standing in the way. I'd be more than happy to review the PR when it's ready :+1:

**Comment by Pacman99** [comment]
Ok awesome, I'm currently working on switching over to flakes, so this might take a bit. But once I have some general home-manager code ready to test with I'll work on implementing it and submitting a PR.
